xray:
    clients: ENC[AES256_GCM,data:yS1MMQio63Z/Tfc/jhsNYke0zMSD9Z1kB4Eg5FtRztmvANY7nTlmlHcrx1MjE+bkcFQq/08xxDQ9uG4jQgKMjkXKrHYIZqXMwYVN+NYKx+pL39HnSvYaqBayss1LmrPxczBcNOZAMOvnB8yCT+b8cgG0WqGjnzDeSrS3Z+mJGFAjplJWyXBxqEVcBN7Hv8VT7HJetLvNJ9XKwvnwAZiJoU6DuHTd1svk/YBpP4Ny+PvkdPDV1oHvvMIqM0IxL1Pref8D+YqKBaanuRvHSqmwxbzNJXjRlLDGVyf9iebQeo9eRAnJ6ETB1T+vRLmZnx0GpmlnVx0BKNolvQytaurYUYO+nr68sLyeLnnA1QSzYOyZcOmV611s0gBkqoQT64IYbdAxNAdJAySphl71BKFkqRFvmoSQzWm1f22quu5xCajuTcQgg9PfUf8uqUvhtQkTjLFiKWo95KlnpzHl7L0t4iM6rX3FBmLDWuhWeIihhXTwaCSyItNfquPvbicJO6p6USjmVcLKH33kWbnnUsJC//ZYSPqj+epaVD7+QcKKwUOKJWlboZkdaqxor7z/4CVkg0LxdxG/uy6H40fCWpqY+2rRE0voAtRui6V6l//x4MY+v2RyL94G01fkNyxIgR+xf2cAqjip5dVk4UlL1tq0LgAPxA5EUkHn7Im41SO6bL3BdUWQJ50FE+RuxHCqWzfjigg2vK6n1dQBzMNWfB7axS+TnDRwmaHnrhswLYWotSCglh0rfpfiCyy/QaSt1nkrY5UgjgJdkQkQ6uo=,iv:AuxUdNZ9WLkiZQsqaCvyGLCCTu8rjJjEy4omeJgahGE=,tag:3D/B/W/xXN5Y4wpiYgHQog==,type:str]
    shortids: ENC[AES256_GCM,data:IM/RKJJ9nivCHEDjLGZ03VvzuOUrq66riNS0wt4irea2rad/SnB+0Y1es5LB7gE3rBwYfKuCJ3vXpoOqNdX8vT49vc/GSRthefiHON5FMAMDk1XqUAb3SsoCf2Tu/PF65a/B,iv:l43t9dV9OgumNwDRy6FamNNc36/Ups/yqj8GwYQmp0M=,tag:RiyRwS7EVEyfCPVGznExOw==,type:str]
    privateKey: ENC[AES256_GCM,data:bSBWWzTT5K/C31Rb4fFoosPjKY78DPStZYlyUe4wlYMS2d3dN8VI5ai0KA==,iv:uooa1bKRzfnVhL3oXxtEwR1d/bTnXckpigRln48tgyk=,tag:KgP4rFJCd9PgYOXjqGPOlw==,type:str]
    dest: ENC[AES256_GCM,data:UtZNyQx5a/4glR5WDOqgjaum4ivItA==,iv:gMld7ujqg0WpikZeSUwLKacpE/yw9If65zGzw1H/vTs=,tag:ByqtW4jibZewhEDu+Fgv3g==,type:str]
    serverNames: ENC[AES256_GCM,data:DgUI9iC9MLlNPc/xuOaSkjNxZkeF,iv:VyUGoXEfD1Xe/j4+6OJaZB3R1L1iTZoYsYQ1pUaqILg=,tag:B13pozoPX+abSTeyOKr8kw==,type:str]
    listen: ENC[AES256_GCM,data:i0FpJV6vwg==,iv:d16/gmByIkZ0vk/7gyeHIvtzdqz8DQdItvvP8WJyeCU=,tag:fNAPK7lzuVvIwvyLv/WBnQ==,type:str]
    port: ENC[AES256_GCM,data:UNv7,iv:GHd/crz6zYAaX3bdw5f541rAHm9Katads6pnP1nITUs=,tag:nwXUHR9ioA/ML7lmZVHz/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14lreqrmnfhvg8q6q200hzqnnu369fmcn85jnwwlyfykpszg8qyyskmp5fs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSDNQZ1Z2VVhPd2UrMm80
            ZDZJTkNXK05MVGJwMVgrQ3JycTJsaEQ5cWd3Cm5MdU5YaGxDOFB1d1Q5V3J1MmpG
            WXVzaGNZZ01mMTRwT3RTeE1saW96SHcKLS0tIHlBZk1lWkJUcWJUTitWV0dpekR6
            UVBDOENCR2JwdnBhdTBaTlRVc0ExTmMKekTy4OIfQiaTKjdh7ONFXpGXXFbsrDVv
            TX6NqW939rxX44hBZozWEusPNFPAJuQFapCB0k+Ckh2czP3vodT1LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T02:59:39Z"
    mac: ENC[AES256_GCM,data:fgMpbbju8YdRRaiBi21+DKPjUz0C318VnJlAfFE31lTPOm5nEYE/dIeD1PvjX0w0xYZyISuYGvZfMM+a3l2wWKR4fRxKasno6/0PRp3WNTtkuTG6rwi1tcWRQUzPTEHvoMMmcfqwhQKSpKLT8ZiVdIQkOnIrURjZDHOdhxqnmK8=,iv:J+TsKUIDOhJQ4Btpo6rwoFH4u9/JOQ39lbfsQRKxDwA=,tag:oSNSsAkoH92wKfYuj1YVOw==,type:str]
    pgp:
        - created_at: "2024-01-21T02:08:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZK5XRnTLNZYSAQdAQTBown/CXDJ5W3epGIG56oM1zt9LSvZxpL3Z8Vsv1Rcw
            snohUxOAmzZdTUK4SU+FJP0nAyUgCCT7eghgoYVwEPj9xSmWNeKgdCkc5RRFU1Ig
            1GgBCQIQTGL01Uz/zM8DFotvw1vZvJG/7hzTqZjhv6oZl2ogTkcIYSqeeP0Q1KiW
            QW4lKvxzrnlcJHnybf9MMBqdzBPDWL5hBwe5y4bJF+3pftXUwbTkloY41Ah9Fn9t
            /boH5O+V60DopA==
            =J2/M
            -----END PGP MESSAGE-----
          fp: AC0D2AF17C37D2CD794292260E6FD23B84E08D57
    unencrypted_suffix: _unencrypted
    version: 3.8.1
