u2f_keys: ENC[AES256_GCM,data:J7GVSc7M36gHY/7eZCk519Q6qSqus2Nfz1sJSH1iaKxtplHZqsBiIwtvMhF/6Qpor95Zrz0S3MaJU9Ax5yL6KBv0T74b50cqEU9ObOWfSqlAIHljadTXuqMRxJR+IR++eEAxeNHUYysOiMWUKsxfXD7ZlqbmvuJL1PPJJlmuJxDr1SmFFbtk+XbqAKnJR+9m4YZPaPU4HYvUSpAZpHLLTPFBcAlxQc7uh1eBdyfd8/ToBy7OUkpIYaSShu32YQJmxDJbg3QSZJ3qte8EirrCRWHgoPDr,iv:2JVaF4uiBNNnZCa5p/tKeLIRBcwgPfE3/RtJ/IKxJ3M=,tag:WLEksbYU2vc8bGK2kjBHZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10j2wx70mg94r7wwtwx7lgmllhewap2cs5c7w4rj9fh9zqkr4rp9s9k5n7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVGZ0OFgyR3lMelZRRGVj
            VkNQQkVrVlErMjlPK3FFWmFvc2NzazF1b3lvCmdRN0pxUzkzOHZQY2pJWldPTnpS
            eExMRyt4S2hHR2FES3A1VUZLNkV6c0EKLS0tIHFrc0FaRUM4MnBYNWI4QnRRSXBw
            cFdJSWV4VC9QSG9ZZUIrdUJrZHYzRDgK1ysRbS1AIlPJzIFaDSIeQRlaGgmD8QGp
            nwCcML/1lkHoyEqKGVOwFjL139VtUIj9z/DqICZ0puMGt0opVconzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T08:02:30Z"
    mac: ENC[AES256_GCM,data:4jeVrp8c7wI07tKm19+3IrUfBWgnQ6Va8YdqW2qHcAsd/FiLt1w8D8+Ymn92CNmDh3KLL/ZwHcPA+3zfkncMe/GoMM89CBUq4JfHjg48J15lZn7a9RAEhLdnezEibLx1O+4EcZ+Nrl7WyOV0fwcsB3HYpFA7yvkbxzOyuz29uIU=,iv:fVl1wTxhaW91sMdRmPUMG99qzZY6mVfa8bK/nZ2N2Cs=,tag:KHOTe2vMMvle+fk6NyRCmg==,type:str]
    pgp:
        - created_at: "2024-01-11T08:02:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZK5XRnTLNZYSAQdArQxNQoTZSPb+13tnrTnhsKc2EN+x/2wcrGa9NDYbZRYw
            7auYS7iwUGdITEsmjYvKU7X4LfN6jQDkYqB/i/GB2fyTMTCQM6OpeBwNcHM48SYy
            1GgBCQIQ+mo7miKO6+OIdghlLrRPGmL4j70fYf0bCeCRs/6bWXUwFZcdsUKc6tNR
            ggSrNvT+fW/Xycq/3yPYX35XynQjgcK41JuAsI4ntd93mfSV12bLx1NpcusgTyY1
            2h0t3GkwefVQWQ==
            =UXYM
            -----END PGP MESSAGE-----
          fp: AC0D2AF17C37D2CD794292260E6FD23B84E08D57
    unencrypted_suffix: _unencrypted
    version: 3.8.1
