users:
    azurcrystal:
        passwd: ENC[AES256_GCM,data:I18CK8CszYJyAgh9Q5pEBp/n5K+LM9CilaE2qNl3O46O6Fb4dchRfNbTYwi7yGwyRtGS0bwzggS/m57xdFicCbQjg4oQugrU2nNvCKVSqtR+O2nm3PHQ38Z9JpJsTFVj67QTBTECe84bPA==,iv:WnxU08N8V3MUHG10Fomu+p2yFms46wEGI+rJhC8bAGM=,tag:gfzaF5+kBriWeCMHRKle+w==,type:str]
    builder:
        key: ENC[AES256_GCM,data:t3DKH5eKT75xwZFOLXILWoRq2eNwcpT6YkWdntU9hEbV81ys1GEpc9LNUfrwEpPUuzKPS5sYxFga5/VEyb78yDrIRKuVaXhaccuJXx60eFre93Rxy7jVQRvXbb6pMftXqEvZm5WZkvkC27FcE4AXvf84zP5FQdvd7KgQtmeuGqsxAXlsvmvDm1A9n6CvD7+Ev/Fp9y5klCFM6mSF8VrnB7Gk2huzPmcFEhIjRtnbJfEQF1q8AmwdR8Kr/dP8TyrBR6ULGDX0keCMDpySR64C4s18vCnkTeL1DQPxm6I5PQx3ACCdDUy4TGXA8HWmLnI1SX04ya6unZXa5DDFwcuEAheEKMW+D1pgZWuSi76KBrSKnmotr74v2/TccMEoTBLkU/xhKZo1hyLK1SHeJxp8u/Xfm0cdZI5Oj/mjlvO1eQZOHapE8tv9fu+hm6a8/xTRuZZ1agHw7wmcE28/zvw7fRGdRSDz4yTtAnnTYQREuv4zUJuy26HuRx6ohCdVIgG1cji0sawSvstmg3GOoc2MzutQxHoD0/TE1rQK,iv:3/7oJotI+YMV7h4gIgICOZVmeEs7L2MTnBNYKqo17Ek=,tag:GEQEB/NQTf5m+ylsUKFEKQ==,type:str]
hosts:
    kvm-aliyun:
        ipAddr: ENC[AES256_GCM,data:MVlR7pdKKOSDUKggWw==,iv:Gm42TEQP0YbCagx2zdhu6+OjfsdZJLyWC4jTL0jnxMc=,tag:Hu35kEmuYSv9xwx7ebJwRQ==,type:str]
    lxc-kabu:
        ipAddr: ENC[AES256_GCM,data:AZNcDz8H1hvEn4E=,iv:KDAJSInTch9wOE8zplwfUgiX3G/9BNDqkxSEpgjkrQw=,tag:JvDTA4UDkq/aXVvtDLcdIg==,type:str]
        ipPort: ENC[AES256_GCM,data:KKpEpDA=,iv:M8Qf3n/s4yR51e/eVDkT3slKd2nVMwU6TBoet3rpxPE=,tag:cDVHvIp2bRegQoVJ3wFVtA==,type:str]
    wsl-main:
        ipAddr: ENC[AES256_GCM,data:O+oXwAuHtxf16Q==,iv:rM8uPz849J97r98BTqPUYZNnmLB39mpi38vUy9qA3Ng=,tag:KbzzEE4+c7ezb53ohBuqYA==,type:str]
    kvm-us-1:
        ipAddr: ENC[AES256_GCM,data:bf+Ry9qAUplxz1As/g==,iv:UePCtdKFCuevYUzWEd3AmtQltAp/x+EMSgpwGWqJFZg=,tag:w0yINdezTFzleIwWV8GBTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10j2wx70mg94r7wwtwx7lgmllhewap2cs5c7w4rj9fh9zqkr4rp9s9k5n7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVzJoUEsvZ01zS045Q1BD
            dEw1NmZNZklXYUxsODRGYmFva1dNcHUvVldVCjNMRHdJaW5xblNPRERBL25zcTBC
            MGR1dCsxOEt4NVBOTGlpRlFUTEEyOGMKLS0tIGxEOG1OeHJyOExzZjVNNUpjajdK
            OGg0QmM5TFNKWldhcVd5SmRaWkRlMWsKJ5lPtE63qY30T0peQfil0pY+KGM1hqV0
            g6KHb94txcN+Obte15qSTBR3CnDr59wUFGS4XyL/LvOG6vC9A4DmlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sczh8f408gd03v0avz8at3a3772yn3xjsu2ca68w02vqhfkv0f4qslcwwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdEduSUl0djludFpzWjRF
            SDRDS0tWM0VKY3dHdDhFUjZEOVEwNk9CRFJjClVQUnZsUVAweDhPT013K00zOC95
            Y3VxeEVWLzVkYTFETmRvZ2pVOFdwZHcKLS0tIE9HdlErY3VWSHZ6SWdnKzN1aENE
            TGM1WUVHamVyNm9vQXNSd0dlVWZDL2sKtSLBC/CbhSMOFLChU5w1sffjkiRoaSpX
            s5ElPCCEt7GMBHanN2Tbn+N1zP19EfcR9T2lKdZs/BI+rsiqIDY9Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rz4ygkquevykurq6rlf25mymxcpg688x840cqqyzewqcaakrnf8schj3nw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhME9TTkZGemN5R09JMzl3
            Yk5NZW1KZDhreno4MXU2dG03eDJWTWl4QzNvCjlDWHY5RlNoazJmUVV5Rmh2azNu
            bXBiYm5VYmpKUWJZeFg1VG5jRGJBYmcKLS0tIGkwd2FpR1hSSXlENDkxVVg1a3dk
            MTJ1ZjVyRjhKejlsUjF2VE1qeTFGSEEKPtbQWwayzCUBqH4vC93yX4cuyC8F8x9S
            0sozE0uHe3ojsPr43izU0WhH65c2fLhEsMAKwLVYbyY/kspus49TMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15n25artefatpem8cr3vrujh5lv85dxfly5829w8gmfamymxl83fszqxgxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ25xbWhwSFJhQWNjQXVB
            SVdkTDY1WE5uRmxud2lieFBZbi9IbnVKbWh3CnFKQ3pVSWhKcGw3R01JZjhHZXpN
            cVBWN29rNmNWOGRvVFlacGtDRFJxOWMKLS0tIDk4WmRLYmNqNFpRdTY0U05NdVZo
            RDhQRUl3WWY1ZDM5UkJhWmt1dy83N28KqH6CrhylQwN9sNBVKAPGG60qoAmpShTu
            u77Bhg2OV31mxoQjCzWg3Aq/akp+H1u9bLG0EMdiCN95oQKwL+zEaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14lreqrmnfhvg8q6q200hzqnnu369fmcn85jnwwlyfykpszg8qyyskmp5fs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MUxwTjBKMFVhUmNKVmUw
            eWJZRm9hNFc3VjF4VmRDRkJiMVpwRm8rZEU4CmNxYVFTVnpCUlM4K01ZNGxGYVpa
            RWltdE10M1pCa0FoVTFmZFF2bWdkVk0KLS0tIHQ2aHpHbEE1SXFoVGZPVHdURDhN
            aTE2Q28zcjhYKzgwWUswb0NqdTdVUE0KzX6UmMnba5TtOZpNH8zQED0YH9UXo9ZT
            os8e+tgqcCx5w46pxKiYecjQ8UbppwaXkAn+HSQIZxAq4mMPyXibgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T06:56:32Z"
    mac: ENC[AES256_GCM,data:cZ4bErFivTySnhqLqylF1C8CYcM+36Q0p5euEg+P4lSfQGCzjwTIAwkOHPPf4gIDjsQlhwdLI5KyIf2QAo0UgxwHRojXfOA3PDBzg8cs84Dq1zW71Z+dz7Qs3rtPKuCzQxr5kpk2laxMBBV+4NXhkmWiEcNRjNxR/ACTN5mBU/A=,iv:6bUkfkcoYJ1FT91nZDahseEr6JJjg1Kw6B+D402+D2Q=,tag:BLa0RFZy2a67E3DLFWUxHQ==,type:str]
    pgp:
        - created_at: "2024-01-12T07:42:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZK5XRnTLNZYSAQdA4nIumyifdE4Iyoj4fwqkWcFPDAae/bewK3a2wX+QhFww
            cDZKaQIyvQnYeXpKcKIQqX8dqQp9CosE7FNru8fox0X2gA+zTizFA8Rf/XfOjUmG
            1GgBCQIQEje07uidzXjfko96viWQkzYGgyOKjOIu7qTr3fm2oBfaw731eYZJkcBl
            Lb+79jmyzj0LC+mPdqMKhJoVZsNZ+PXK+OqtW/zbzOw4qvPBi/9uJ4lwLRvKQfvK
            RI2HSlcUewR2Zg==
            =zkMY
            -----END PGP MESSAGE-----
          fp: AC0D2AF17C37D2CD794292260E6FD23B84E08D57
    unencrypted_suffix: _unencrypted
    version: 3.8.1
