users:
    azurcrystal:
        passwd: ENC[AES256_GCM,data:I18CK8CszYJyAgh9Q5pEBp/n5K+LM9CilaE2qNl3O46O6Fb4dchRfNbTYwi7yGwyRtGS0bwzggS/m57xdFicCbQjg4oQugrU2nNvCKVSqtR+O2nm3PHQ38Z9JpJsTFVj67QTBTECe84bPA==,iv:WnxU08N8V3MUHG10Fomu+p2yFms46wEGI+rJhC8bAGM=,tag:gfzaF5+kBriWeCMHRKle+w==,type:str]
    builder:
        key: ENC[AES256_GCM,data:t3DKH5eKT75xwZFOLXILWoRq2eNwcpT6YkWdntU9hEbV81ys1GEpc9LNUfrwEpPUuzKPS5sYxFga5/VEyb78yDrIRKuVaXhaccuJXx60eFre93Rxy7jVQRvXbb6pMftXqEvZm5WZkvkC27FcE4AXvf84zP5FQdvd7KgQtmeuGqsxAXlsvmvDm1A9n6CvD7+Ev/Fp9y5klCFM6mSF8VrnB7Gk2huzPmcFEhIjRtnbJfEQF1q8AmwdR8Kr/dP8TyrBR6ULGDX0keCMDpySR64C4s18vCnkTeL1DQPxm6I5PQx3ACCdDUy4TGXA8HWmLnI1SX04ya6unZXa5DDFwcuEAheEKMW+D1pgZWuSi76KBrSKnmotr74v2/TccMEoTBLkU/xhKZo1hyLK1SHeJxp8u/Xfm0cdZI5Oj/mjlvO1eQZOHapE8tv9fu+hm6a8/xTRuZZ1agHw7wmcE28/zvw7fRGdRSDz4yTtAnnTYQREuv4zUJuy26HuRx6ohCdVIgG1cji0sawSvstmg3GOoc2MzutQxHoD0/TE1rQK,iv:3/7oJotI+YMV7h4gIgICOZVmeEs7L2MTnBNYKqo17Ek=,tag:GEQEB/NQTf5m+ylsUKFEKQ==,type:str]
hosts:
    kvm-aliyun:
        ipAddr: ENC[AES256_GCM,data:MVlR7pdKKOSDUKggWw==,iv:Gm42TEQP0YbCagx2zdhu6+OjfsdZJLyWC4jTL0jnxMc=,tag:Hu35kEmuYSv9xwx7ebJwRQ==,type:str]
    lxc-kabu:
        ipAddr: ENC[AES256_GCM,data:AZNcDz8H1hvEn4E=,iv:KDAJSInTch9wOE8zplwfUgiX3G/9BNDqkxSEpgjkrQw=,tag:JvDTA4UDkq/aXVvtDLcdIg==,type:str]
        ipPort: ENC[AES256_GCM,data:KKpEpDA=,iv:M8Qf3n/s4yR51e/eVDkT3slKd2nVMwU6TBoet3rpxPE=,tag:cDVHvIp2bRegQoVJ3wFVtA==,type:str]
    wsl-main:
        ipAddr: ENC[AES256_GCM,data:O+oXwAuHtxf16Q==,iv:rM8uPz849J97r98BTqPUYZNnmLB39mpi38vUy9qA3Ng=,tag:KbzzEE4+c7ezb53ohBuqYA==,type:str]
    kvm-us-1:
        ipAddr: ENC[AES256_GCM,data:bf+Ry9qAUplxz1As/g==,iv:UePCtdKFCuevYUzWEd3AmtQltAp/x+EMSgpwGWqJFZg=,tag:w0yINdezTFzleIwWV8GBTQ==,type:str]
    lxc-router:
        ipAddr: ENC[AES256_GCM,data:swOxyGk0NdYEFxeL,iv:iEtKEFPLHMyCZ8om+zy1rcgG0UyFD/QrSd6EoPhrJXs=,tag:ZjW/lVsumEeIwYVvOvz/yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10j2wx70mg94r7wwtwx7lgmllhewap2cs5c7w4rj9fh9zqkr4rp9s9k5n7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRWJiOTU1Y3RYVDMzclRz
            ZEl2RUJCVEdUWXNuT09adnh4cFpqZ1ZNSzJJCk1MZGdQMFVxUGFZSjMrdmpmcVJq
            MzRWSy9UYTJzTHJLR2l1Zkthb1ZGWU0KLS0tIHdJMzNZWW9xSWNvWEtRS2kvdzc5
            Wnp3UDVRa1lrbjc3a3NGSEd5QzdEdWcKDIpKfHKLPwQL3ebFO9VvDwNmmR23FmqE
            1uy7r3Jsc5Ixti4aQWXgvKSStyp8s7wwyZk7HmeuJ4gltm4/v4PsXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pl9qgavlf32f9dmmj0pnz46sk3kmg9nmps395tn53ad4d4qly3vs7jtqjs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L29jaTZjM1BCYkpOeEdP
            U2h1OHJTREk0ckhjbjBUUlVIeWhjTWlSaWxRCk4xY1NTVmp4a0VIMmpLVFdEZDI4
            QXpSY0Rrd3BjbGwxQngxZEZTTGg0dWcKLS0tIG1YOXZNVEVBamN3MmppbnZGdGVp
            VFBlTXMrdUprZ1pzQnFCOHJIUG55OXMKwcPtIE8yrFl54vWyQ7BsvWlklf/8U9iM
            fmR2l1dzhZUOLa48P1jQNP2O3mWSdu8tX6TWgS8BwkLB4Y206TYWQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rz4ygkquevykurq6rlf25mymxcpg688x840cqqyzewqcaakrnf8schj3nw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVDBzOWRTckRRNE1MUUhZ
            OGd1S2VGc2dLY1BpWjF3RzVCOVVLSnIyc1MwCkdheXNHOHFQWVpJK25tdkZKSVlw
            M1o1YXdkbnFPeU5LUmxkUEMrYkc4dHcKLS0tIFJyU3lBcGRwTWdzM0ZRK3IzT0Fy
            MnEvb1lVN1NQYWp5OVBnaXBDQzFWNzQKVxh1LT76/VXqAuD32bW5IT9z1fTHOUkX
            RaY6IA5cUTfATgypE7UCIJZyYEza4dObxdtNLhjBpDdWjxj7iQ44cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15n25artefatpem8cr3vrujh5lv85dxfly5829w8gmfamymxl83fszqxgxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdWlwaENMQllEOGVIclNN
            amk2M3REUG5VV2FTUGRURXl5Z3NjRkhOSVJzCms3dDcwb3paVjlDMlZtQUZBMUd0
            ODdYelpYNkpUMlpvNkd1UVpVckdBYWMKLS0tIEE5SDlmUGVuL3NyZUZ1d3JiS1la
            cWtFOHZSaW9HNVkzSWtCa01lSW82S1UKLa33thB941p4yPg4CXxcm+kQlDKhyUmV
            vTPzOdzl40spJi1a+iYSEqm1P7lpATymrovvGqX2VGWjH1HgZiRqMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14lreqrmnfhvg8q6q200hzqnnu369fmcn85jnwwlyfykpszg8qyyskmp5fs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMkVsZ1Zaa1VkMWZRdWNp
            Uk5QYVhkU2dMUUdzcUJxWTZ5NzYxckFDMkJRCldpQXJocURxZk9jMm00UXJLMytZ
            ODFRNktaS1YxWXo4ekdnZUl5QW1BQ0kKLS0tIE5RQ05aUEFIaW9rL01henRNejJi
            azdjMG9FUWRrbW53dTlBcXFKZXJGMUkKgDG6O5yfb+BDOrzo/9bnjWV3bb3Gbp4i
            3ngkChFfo8544O7rGDGrsScB5gjQyGpYkmu6Q/5w+QBw8NXJTjUFYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age148prq7fcht7lnnsjp76kctlp2kl9jr67vvfy9tf8yvhtm9y8y3cqv9cz42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU0krLzMvZkQzZDFUeUJZ
            V1RhRUlRNXlEMC9KUkRCbEFGSGJYcThOSm1JCmN6SmkvZ0QxamxpOHNEbGZSSUY3
            UmtqaE0zZ3J4UVJqRW53ajhFYjNvRmsKLS0tIEZRYWdHZ3pYdUtycFFsMFI3Q1Zo
            dHFxNjZxaTNHVzVGR0NTcEE5ai85MTgKJ5sRlbdVVT+6di0my07CiDVYzIqizCT1
            vLTtQAgAaUaK9cRVJARDiaYyJp439iAE/qcCUrmM5rL4qHcDF7UrVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T03:28:21Z"
    mac: ENC[AES256_GCM,data:81GXjlReAtWvmPommFJVOd7kJSdbSIt+nyKWIgDUHnqhTBOLVgCJfkj9FBy8AmGDiJT384sfJ7Qp5aBi+ypwJgCUF+Z2lhGcJ3EfTK3ZhBdqovGqGXMFTfMvYNbUjGxYHhzBJXdpcClv6rZXRau/YJztAhvKOjswOgL8MvUL+lo=,iv:/YaYfJAihG2dM3hotT0ZvknBQODhHRSHgKvgdB+c8nQ=,tag:AXCi8Xq2Zr/hZEyHbaR4Ug==,type:str]
    pgp:
        - created_at: "2024-03-10T13:19:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZK5XRnTLNZYSAQdAiL/4JISH8PxJx2y/6xg2BRb5MPrDFPH7Qszu9Ku8ESgw
            W7jZjV+HQrmy+s4lOdhwCxB89KJ5dAUX8wMtrsQPPIw3TRfeCdOLVPoD1cr5nSMZ
            1GgBCQIQI5lY+KThqvwfjRX3dYWnGER6U8WDotJIb9p7Z4/2qqD0Q1aic883zcDl
            ghiMVVgXotPKj+g7p1/3a8kW+sVZzR9wt5XzmGYk4NED3lQwzsDaT2R2bBSi/vO3
            UpUekhtmyATnGA==
            =qz20
            -----END PGP MESSAGE-----
          fp: AC0D2AF17C37D2CD794292260E6FD23B84E08D57
    unencrypted_suffix: _unencrypted
    version: 3.8.1
