users:
    azurcrystal:
        passwd: ENC[AES256_GCM,data:I18CK8CszYJyAgh9Q5pEBp/n5K+LM9CilaE2qNl3O46O6Fb4dchRfNbTYwi7yGwyRtGS0bwzggS/m57xdFicCbQjg4oQugrU2nNvCKVSqtR+O2nm3PHQ38Z9JpJsTFVj67QTBTECe84bPA==,iv:WnxU08N8V3MUHG10Fomu+p2yFms46wEGI+rJhC8bAGM=,tag:gfzaF5+kBriWeCMHRKle+w==,type:str]
    builder:
        key: ENC[AES256_GCM,data:t3DKH5eKT75xwZFOLXILWoRq2eNwcpT6YkWdntU9hEbV81ys1GEpc9LNUfrwEpPUuzKPS5sYxFga5/VEyb78yDrIRKuVaXhaccuJXx60eFre93Rxy7jVQRvXbb6pMftXqEvZm5WZkvkC27FcE4AXvf84zP5FQdvd7KgQtmeuGqsxAXlsvmvDm1A9n6CvD7+Ev/Fp9y5klCFM6mSF8VrnB7Gk2huzPmcFEhIjRtnbJfEQF1q8AmwdR8Kr/dP8TyrBR6ULGDX0keCMDpySR64C4s18vCnkTeL1DQPxm6I5PQx3ACCdDUy4TGXA8HWmLnI1SX04ya6unZXa5DDFwcuEAheEKMW+D1pgZWuSi76KBrSKnmotr74v2/TccMEoTBLkU/xhKZo1hyLK1SHeJxp8u/Xfm0cdZI5Oj/mjlvO1eQZOHapE8tv9fu+hm6a8/xTRuZZ1agHw7wmcE28/zvw7fRGdRSDz4yTtAnnTYQREuv4zUJuy26HuRx6ohCdVIgG1cji0sawSvstmg3GOoc2MzutQxHoD0/TE1rQK,iv:3/7oJotI+YMV7h4gIgICOZVmeEs7L2MTnBNYKqo17Ek=,tag:GEQEB/NQTf5m+ylsUKFEKQ==,type:str]
hosts:
    kvm-aliyun:
        ipAddr: ENC[AES256_GCM,data:MVlR7pdKKOSDUKggWw==,iv:Gm42TEQP0YbCagx2zdhu6+OjfsdZJLyWC4jTL0jnxMc=,tag:Hu35kEmuYSv9xwx7ebJwRQ==,type:str]
    lxc-kabu:
        ipAddr: ENC[AES256_GCM,data:AZNcDz8H1hvEn4E=,iv:KDAJSInTch9wOE8zplwfUgiX3G/9BNDqkxSEpgjkrQw=,tag:JvDTA4UDkq/aXVvtDLcdIg==,type:str]
        ipPort: ENC[AES256_GCM,data:KKpEpDA=,iv:M8Qf3n/s4yR51e/eVDkT3slKd2nVMwU6TBoet3rpxPE=,tag:cDVHvIp2bRegQoVJ3wFVtA==,type:str]
    wsl-main:
        ipAddr: ENC[AES256_GCM,data:O+oXwAuHtxf16Q==,iv:rM8uPz849J97r98BTqPUYZNnmLB39mpi38vUy9qA3Ng=,tag:KbzzEE4+c7ezb53ohBuqYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15n25artefatpem8cr3vrujh5lv85dxfly5829w8gmfamymxl83fszqxgxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN2RQaXU2S2owTkc4dDN1
            M1JXWGNneEVmR3JpekZuWkNiSHdwaFRPaUU0CjJMT3cxTUxHMmExNjAvSGlLR1VU
            YUZFSzRFRVAzYkdFQW5QYkxnY0NZMm8KLS0tIEJFMjFDWHVpa3FmT013L2dua24z
            WVJlWjg3d2svRXNSdGE2cWZJWWc4QVEKsaH+FbrprZPZLOJMmvlHoH5VGjFBASxu
            Fe1WsezBgSt++lt9T3OrqChY+dnT5e0QDvCyOBt2nrczdeELutUW0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rz4ygkquevykurq6rlf25mymxcpg688x840cqqyzewqcaakrnf8schj3nw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z0xLYnp2Rk1ZZytEU2VZ
            R2pHMExXNGFTdGNPMUNsZUZCeWhiU1Q2cDJnCmUxcGNtR0dDbU4yaVRyQmhMZ2o3
            eU1TZHFpNXE0NFUvelUvVkFQZmVwVUEKLS0tIEl0TUFvZGFjTGswK0ltU3VveEt4
            enphYXdmZ2lxN3JaWHhLK2htcmZ3d0EK8l/n3OtAarbYk0O/Q20KdcyWLU71SQ3s
            mUp5hr9Zki3SPP6QmxuqefGE7B5xJTA82NpF+JAdWylf/WYD2uaJ9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sczh8f408gd03v0avz8at3a3772yn3xjsu2ca68w02vqhfkv0f4qslcwwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmEwTnd6K1FlSnJjR2hi
            MUpCOEpmdTQ4cW1tbW1YRnBLSVlyTldWM3lVCkVaZ0xPVmxCSVpTM05jcEJrdXZl
            TTVUTklkMW1FS0ZlUy9mMHVMK3ZCWkkKLS0tIGVZalpQczlUclRabDcwUnRGczZw
            RDk3WnpIaWN1ZEhGZktTQjFTNEduU3cKC1gZjB4oy7QxISAC3bAF8C+GJ6mlwP0O
            pO0un/gRbcXfntIo7KiLt5ezkcFSgG/yF+Ht1ZJEJ4ZI457oEd6LNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10j2wx70mg94r7wwtwx7lgmllhewap2cs5c7w4rj9fh9zqkr4rp9s9k5n7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY3JDcnNCQ29Rdnc2QkxV
            L0liTytsNmxRUzhnU0VhSlB1TVNocFFsTnk4CktTUHlVMHM2T3UrbjZTV1B1WUlk
            WldZRklPaGdZV0dLY0h4NGtPdmZSbHMKLS0tIHFTWkk0TVREOXBFTnRkOUlVbUJ2
            T2ZXdlVtTEYvcGJqeGw4WFZ6WlpyNGcKWKKB6VBoJjxr6NORmI6GQNAb4s/deuhR
            AAnARUwgHdbuS7eeFELCZmx4EJmacqRfom6bwUDNmFtZWCKHF6UtRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T08:00:39Z"
    mac: ENC[AES256_GCM,data:7dvsHa3NtxZbaZhj5X/uLlMO23uEAsxA1FmOS55OBrePAEWBXojDdkJByHXVVmglKSZllGFPZnQB/cAAjygoQRYmhjIztuPX8sN6FXgighFOeVdLIThTre9gbXA9wZglLPQv9Wqqan1acqkUIEEWzcsGP7R3yY2WOzrvJWD2l/o=,iv:o8bCIw8bfcaVYVCx0LPU/bgVag/eF+NDV8PSC9RFCek=,tag:7A4nBOs7wNi7cjk76LiUvA==,type:str]
    pgp:
        - created_at: "2024-01-11T01:59:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DZK5XRnTLNZYSAQdAigaxk18H9SmnqIzzZ/zmlq1Ce3d9lYetTIvBGt5csiQw
            3NGV43vNlbuZmM0i6dg9T8tqNyrkac3F/Rs9UH1jGy+YjmdZrWUus7axGd5ZpAic
            1GgBCQIQ6S75dl4nAu5abza+f3ugShDknfByyCM0jgnIo09h7eRvWRArpKG5VxnK
            A3e6hKzp0XPsTsk3X9azYzCrKSLCmV0jiJxZU7/vHrt4EDY6GINxO3SvehnylXmy
            YBXg7qGELsa9hQ==
            =A1NQ
            -----END PGP MESSAGE-----
          fp: AC0D2AF17C37D2CD794292260E6FD23B84E08D57
    unencrypted_suffix: _unencrypted
    version: 3.8.1
